version: 2.1

jobs:
  test:
    docker:
      - image: alpine:3.14
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: docker v
        command: apk add docker
    - run:
        name: docker v
        command: docker --version
    - run:
        name: python v
        command: apk add python
    - run:
          name: python v
          command: python --version

  report:
    docker:
      - image: circleci/python:3.1
    working_directory: ~/repo
    steps:
      - run:
          name: python v
          command: python --version

workflows:
  version: 2
  build:
    jobs:
     - test

     - report:
          requires:
           - test