version: 2.1

jobs:
  test:
    docker:
      - image: alpine:3.14
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: install dep
        command: scripts/install-depends
    - run:
        name: python v
        command: |
          python3 --version \
          docker --version

  report:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo
    steps:
      - run:
          name: python v
          command: python --version

workflows:
  version: 2
  build:
    jobs:
     - test

     - report:
          requires:
           - test