version: 2.1

aliases:
  - &install-depends
      run:
        name: install depends
        command: scripts/install-depends
  - &run-tests
      run:
        name: run tests
        command: scripts/run-tests

jobs:
  test:
    docker:
      - image: alpine:3.14
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: permission
        command: chmod +x -R ./scripts
    - run:
        name: install depends
        command: scripts/install-depends
    - run:
        name: poetry install
        command: poetry install
    - run:
        name: run tests
        command: scripts/run-tests

  report:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo
    steps:
      - run:
          name: python v
          command: python --version

workflows:
  version: 2
  build:
    jobs:
     - test

     - report:
          requires:
           - test