#!/bin/sh

apk add docker
apk add --no-cache python3 py3-pip
apk add curl

curl -sSL https://install.python-poetry.org | python3 -

source $HOME/.poetry/env

poetry --version

cd ..

poetry --version

cd ..

poetry --version






