#!/bin/sh

apk add docker
apk add --no-cache python3 py3-pip
apk add curl


curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3

#source $HOME/.poetry/env

#poetry env info

#poetry config virtualenvs.create false

poetry install

source $(poetry env info --path)/bin/activate

poetry install

poetry env info

poetry env list --full-path

cd $(poetry env info --path)/lib

ls
