#!/bin/sh

apk add docker docker-compose

docker-compose --version

ls

#docker-compose -f docker-compose.test.yml up

docker run \
  --name test_db \
  -p 3307:3306 \
  -e MYSQL_ROOT_PASSWORD=Password123 \
  -e MYSQL_DATABASE=secc_test_actions \
  mysql:8.0.29 \
  --default-authentication-plugin=mysql_native_password
  -v /var/run/docker.sock:/var/run/docker.sock







#docker --version
#
#curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
#
#source $HOME/.poetry/env
#
#poetry config virtualenvs.create true
#
#poetry install --no-dev
#
#source .venv/bin/activate
#
#ls
#
#cd .venv
#
#ls
#
#cd bin
#
#ls
#
#python3 -m pytest -s

#poetry install

#source $(poetry env info --path)/bin/activate

#poetry env info

#poetry env list --full-path

#poetry show

#poetry run python3 -m pytest -s

#cd $(poetry env info --path)/lib/python3.10/site-packages/
#cd $(poetry env info --path)/bin


#pip3 install -r poetry.toml

#poetry export -f requirements.txt > requirements.txt

#cat requirements.txt

#python3 -m venv venv
#source venv/bin/activate

#pip install -r  requirements.txt

#ls



#

#ls

#python3 main.py






